### ISSUE TITLE
[QUESTION] Open Source physics engine?

### ISSUE THREAD

**Issue by chris-aeviator** [openai/mujoco-worldgen#3]
Thanks for contributing your work. In order to enhance and work with this repo it would be beneficial if an open source physics engine (think e.g. `bullet physics`) could be used.

Are there any suggestions (or forks?) you can point me to to migrate to an OS engine?

**Comment by todor-markov** [comment]
This repository was specifically designed to work with MuJoCo. At this point in time we have no plans to support any other physics simulators.

I'm currently not aware of any forks that have done the migration to a different engine.

**Comment by odellus** [comment]
OpenAI so open
